### PR TITLE
Support Jest 27

### PR DESCRIPTION
**Pull request by ybiquitous**
Jest 27 has been released! 🎉 
https://jestjs.io/blog/2021/05/25/jest-27

> Which issue, if any, is this issue related to?

None.

> Is there anything in the PR that needs further explanation?

This change adds the support of Jest 27. I will create a test PR to the [stylelint/stylelint](https://github.com/stylelint/stylelint) repository.

### CODE REVIEW

**Review by hudochenkov — APPROVED** [review]

**Comment by ybiquitous** [comment]
> I will create a test PR to the [stylelint/stylelint](https://github.com/stylelint/stylelint) repository.

Done. See stylelint/stylelint#5326

**Comment by ybiquitous** [comment]
> @ybiquitous Can I give you npm access to publish a new version?

Yes,  thanks!

> Should be a patch release, right?

Maybe. But I'm checking if this change works on some stylelint plugins, so please wait for a while. 🙏🏼

**Comment by ybiquitous** [comment]
When I test this change for plugins on the list below, I find no breaking. 👍🏼 
https://github.com/stylelint/jest-preset-stylelint/network/dependents?dependent_type=PACKAGE

I think it's OK to release the next version 4.1.1. 😄 
https://github.com/stylelint/jest-preset-stylelint/releases

**Comment by jeddy3** [comment]
> Can I give you npm access to publish a new version?

I wasn't able to as I'm only a _member_ of the package. See https://github.com/stylelint/jest-preset-stylelint/issues/23.

@ntwb Is it possible to make me an owner, so I can invite others to the package for future releases?

> I think it's OK to release the next version 4.1.1. 😄

I've released as `4.1.1`.

**Comment by ntwb** [comment]
@jeddy3 Trying to resolve this now

**Comment by ntwb** [comment]
@ybiquitous There should be an invite to the stylelint npm org in your email

**Comment by ntwb** [comment]
I've added this `` package to the mpm stylelint org

p.s @jeddy3 you're already an owner, I'll continue to follow up and close out #23 all the same

**Comment by ybiquitous** [comment]
@jeddy3 Thank you for the release! 🎉 

@ntwb Thank you for the invitation! 😄

**Pull request merged**
