### PR TITLE
Update deps and CI settings

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

~~Wait for #46 merged~~ Done.

> Is there anything in the PR that needs further explanation?

This pull request does:

- updating all outdated dependencies including GitHub Actions
- simplifying the lint settings on CI
- adding Node.js 18 to the CI matrix

### CODE REVIEW

**Review by jeddy3 — APPROVED** [review]
LGTM. Nice to see everything up to date in the package.

**Comment by ybiquitous** [comment]
I've rebased the main branch. When CI passes, I'll merge this.

**Comment by ybiquitous** [comment]
And, I'll release v5.0.2 including the Jest 28 support (#46).

**Comment by ybiquitous** [comment]
Released 🎉 

- https://github.com/stylelint/jest-preset-stylelint/releases/tag/5.0.3
- https://www.npmjs.com/package/jest-preset-stylelint/v/5.0.3

**Comment by jeddy3** [comment]
It'd be great to use the new GitHub Action reporter in the stylelint repo when we update to Jest 28.

**Pull request merged**
